/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_adobe_plugins_FastCanvasJNI */

#ifndef _Included_com_adobe_plugins_FastCanvasJNI
#define _Included_com_adobe_plugins_FastCanvasJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_adobe_plugins_FastCanvasJNI
 * Method:    setBackgroundColor
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_adobe_plugins_FastCanvasJNI_setBackgroundColor
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     com_adobe_plugins_FastCanvasJNI
 * Method:    setOrtho
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_adobe_plugins_FastCanvasJNI_setOrtho
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_adobe_plugins_FastCanvasJNI
 * Method:    addTexture
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_com_adobe_plugins_FastCanvasJNI_addTexture
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     com_adobe_plugins_FastCanvasJNI
 * Method:    addPngTexture
 * Signature: (Ljava/lang/Object;Ljava/lang/String;ILcom/adobe/plugins/FastCanvasTextureDimension;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_adobe_plugins_FastCanvasJNI_addPngTexture
  (JNIEnv *, jclass, jobject, jstring, jint, jobject);

/*
 * Class:     com_adobe_plugins_FastCanvasJNI
 * Method:    removeTexture
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_adobe_plugins_FastCanvasJNI_removeTexture
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_adobe_plugins_FastCanvasJNI
 * Method:    render
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_adobe_plugins_FastCanvasJNI_render
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_adobe_plugins_FastCanvasJNI
 * Method:    surfaceChanged
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_adobe_plugins_FastCanvasJNI_surfaceChanged
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_adobe_plugins_FastCanvasJNI
 * Method:    captureGLLayer
 * Signature: (Ljava/lang/String;IIIILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_adobe_plugins_FastCanvasJNI_captureGLLayer
  (JNIEnv *, jclass, jstring, jint, jint, jint, jint, jstring);

/*
 * Class:     com_adobe_plugins_FastCanvasJNI
 * Method:    contextLost
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_adobe_plugins_FastCanvasJNI_contextLost
  (JNIEnv *, jclass);

/*
 * Class:     com_adobe_plugins_FastCanvasJNI
 * Method:    release
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_adobe_plugins_FastCanvasJNI_release
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
